#!/bin/sh
#
# PROVIDE: reticen8-tincd
# REQUIRE: SERVERS
# KEYWORD: shutdown

. /etc/rc.subr

name=ostincd

stop_cmd=ostincd_stop
start_cmd=ostincd_start
rcvar=ostincd_enable

load_rc_config reticen8-tincd

[ -z "$ostincd_enable" ] && ostincd_enable="NO"

# stop tincd
ostincd_stop()
{
	echo "stopping tincd"
	/usr/local/reticen8/scripts/Reticen8/Tinc/tincd.py stop
}

# start tincd
ostincd_start()
{
	echo "starting tincd"
	/usr/local/reticen8/scripts/Reticen8/Tinc/tincd.py start
}

run_rc_command $1
