PLUGIN_NAME=		qemu-guest-agent
PLUGIN_VERSION=		1.2
PLUGIN_COMMENT=		QEMU Guest Agent for Reticen8
PLUGIN_DEPENDS=		qemu-guest-agent
PLUGIN_MAINTAINER=	reticen8@moov.de

.include "../../Mk/plugins.mk"
