PLUGIN_NAME=		wazuh-agent
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		Agent for the open source security platform Wazuh
PLUGIN_DEPENDS=		wazuh-agent
PLUGIN_MAINTAINER=	ad@reticen8.com

.include "../../Mk/plugins.mk"
