PLUGIN_NAME=		etpro-telemetry
PLUGIN_VERSION=		1.6
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		ET Pro Telemetry Edition
PLUGIN_MAINTAINER=	ad@reticen8.com
PLUGIN_WWW=		https://docs.reticen8.com/manual/etpro_telemetry.html
PLUGIN_TIER=		2

.include "../../Mk/plugins.mk"
