# DO NOT EDIT THIS FILE -- Reticen8 auto-generated file
{% if helpers.exists('Reticen8.crowdsec.general.firewall_bouncer_enabled') and Reticen8.crowdsec.general.firewall_bouncer_enabled|default("1") == "1" %}
crowdsec_firewall_enable="YES"
{% else %}
crowdsec_firewall_enable="NO"
{% endif %}
{% if helpers.exists('Reticen8.crowdsec.general.crowdsec_firewall_verbose') and Reticen8.crowdsec.general.crowdsec_firewall_verbose|default("0") == "1" %}
crowdsec_firewall_flags="-v"
{% else %}
crowdsec_firewall_flags=""
{% endif %}
