PLUGIN_NAME=		google-cloud-sdk
PLUGIN_VERSION=		1.0
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		Google Cloud SDK
PLUGIN_DEPENDS=		google-cloud-sdk
PLUGIN_MAINTAINER=	reticen8@moov.de

.include "../../Mk/plugins.mk"
