# DO NOT EDIT THIS FILE -- Reticen8 auto-generated file
{% if helpers.exists('Reticen8.crowdsec.general.agent_enabled') and Reticen8.crowdsec.general.agent_enabled|default("1") == "1" %}
crowdsec_enable="YES"
{% else %}
crowdsec_enable="NO"
{% endif %}
{% if helpers.exists('Reticen8.crowdsec.general.lapi_enabled') and Reticen8.crowdsec.general.lapi_enabled|default("1") == "1" %}
crowdsec_flags=""
{% else %}
crowdsec_flags="-no-api"
{% endif %}
