# DO NOT EDIT THIS FILE -- Reticen8 auto-generated file
{% if helpers.exists('Reticen8.relayd.general.enabled') and Reticen8.relayd.general.enabled|default("0") == "1" %}
osrelayd_enable="YES"
{% else %}
osrelayd_enable="NO"
{% endif %}
