PLUGIN_NAME=		upnp
PLUGIN_VERSION=		1.5
PLUGIN_REVISION=	5
PLUGIN_DEPENDS=		miniupnpd
PLUGIN_COMMENT=		Universal Plug and Play Service
PLUGIN_MAINTAINER=	franco@reticen8.com

.include "../../Mk/plugins.mk"
